base_url: 'http://www.ambito.com/economia/mercados/monedas/dolar/'

blue:
  buy:
    xpath: '//*[@id="contenido"]/div[2]/div/div/div[2]/big'
  sell:
    xpath: '//*[@id="contenido"]/div[2]/div/div/div[3]/big'

official:
  buy:
    xpath: '//*[@id="contenido"]/div[1]/div[1]/div/div/div[2]/big'
  sell:
    xpath: '//*[@id="contenido"]/div[1]/div[1]/div/div/div[3]/big'

card:
  sell:
    xpath: '//*[@id="contenido"]/div[4]/div/div/div[2]/big'
